Traceback (most recent call last):
  File "C:\Users\chenoi\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\chenoi\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\chenoi\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numba import njit
from scipy.special import factorial2

@njit
def sample_moments_ar1(k, m=100_000, mu_0=0.0, sigma_0=1.0, seed=1234):
    np.random.seed(seed)
    sample_sum = 0.0
    x = mu_0 + sigma_0 * np.random.randn()
    for t in range(m):
        sample_sum += (x - mu_star)**k
        x = a * x + b + c * np.random.randn()
    return sample_sum / m

def true_moments_ar1(k):
    if k % 2 == 0:
        return std_star**k * factorial2(k - 1)
    else:
        return 0

k_vals = np.arange(6) + 1
sample_moments = np.empty_like(k_vals)
true_moments = np.empty_like(k_vals)

for k_idx, k in enumerate(k_vals):
    sample_moments[k_idx] = sample_moments_ar1(k)
    true_moments[k_idx] = true_moments_ar1(k)

fig, ax = plt.subplots()
ax.plot(k_vals, true_moments, label="true moments")
ax.plot(k_vals, sample_moments, label="sample moments")
ax.legend()

plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mSystemError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_30488\221731253.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mfrom[0m [0mnumba[0m [1;32mimport[0m [0mnjit[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0mspecial[0m [1;32mimport[0m [0mfactorial2[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [1;33m@[0m[0mnjit[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mdef[0m [0msample_moments_ar1[0m[1;33m([0m[0mk[0m[1;33m,[0m [0mm[0m[1;33m=[0m[1;36m100_000[0m[1;33m,[0m [0mmu_0[0m[1;33m=[0m[1;36m0.0[0m[1;33m,[0m [0msigma_0[0m[1;33m=[0m[1;36m1.0[0m[1;33m,[0m [0mseed[0m[1;33m=[0m[1;36m1234[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m     40[0m [1;33m[0m[0m
[0;32m     41[0m [1;31m# Re-export vectorize decorators and the thread layer querying function[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 42[1;33m from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
[0m[0;32m     43[0m                             get_num_threads, set_num_threads)
[0;32m     44[0m [1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\np\ufunc\__init__.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# -*- coding: utf-8 -*-[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0mdecorators[0m [1;32mimport[0m [0mVectorize[0m[1;33m,[0m [0mGUVectorize[0m[1;33m,[0m [0mvectorize[0m[1;33m,[0m [0mguvectorize[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0m_internal[0m [1;32mimport[0m [0mPyUFunc_None[0m[1;33m,[0m [0mPyUFunc_Zero[0m[1;33m,[0m [0mPyUFunc_One[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m [1;32mimport[0m [0m_internal[0m[1;33m,[0m [0marray_exprs[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\numba\np\ufunc\decorators.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;32mimport[0m [0minspect[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m [1;32mimport[0m [0m_internal[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;32mfrom[0m [0mnumba[0m[1;33m.[0m[0mnp[0m[1;33m.[0m[0mufunc[0m[1;33m.[0m[0mparallel[0m [1;32mimport[0m [0mParallelUFuncBuilder[0m[1;33m,[0m [0mParallelGUFuncBuilder[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mSystemError[0m: initialization of _internal failed without raising an exception
SystemError: initialization of _internal failed without raising an exception

